### ISSUE TITLE
Shouldn't create unnecessary directories.

### ISSUE THREAD

**Issue by psachin** [bhrigu123/classifier#10]
I noticed that even if there are no audio files, it creates a directory 'Music'. This happens for other directories also. Please avoid this. If the file-formats are not found, don't create an empty directory.

**Comment by Endi1** [comment]
I can fix this if the maintainer wants. I'll submit a PR shortly.

**Comment by psachin** [comment]
PR is most welcome.

**Comment by bhrigu123** [comment]
Fixed in PR 6ce5c7061c264c5cc327f86b49301fdb23d6d70e
