### ISSUE TITLE
Issue with archive extensions

### ISSUE THREAD

**Issue by DrNightmare** [bhrigu123/classifier#13]
`os.path.splitext('example.tar.gz')`
returns '.gz' as the extension, and not '.tar.gz' as expected.

Same issue applies to tar.bz2 files.

One fix would be to change the extensions in formats from *.tar.gz* to *.gz* and *.tar.bz2* to *.bz2*

**Comment by bhrigu123** [comment]
Fixed from PR
0ff8e8d0fa2a52f13f412a91bfa9103602c017b5
