### ISSUE TITLE
Windows Support (Feature Request)

### ISSUE THREAD

**Issue by manu-chroma** [bhrigu123/classifier#18]
Hey, 
I really like the idea of this python module you have there. Why doesn't it support windows for the time being ? I mean what are the restrictions and problems you're facing ?

**Comment by RealJTG** [comment]
It actually works if you run `python classifier` directly, just need some tweaks in setup.py

Sending a PR https://github.com/bhrigu123/classifier/pull/24

**Comment by manu-chroma** [comment]
Working alright on windows now.
