### ISSUE TITLE
Support for Programs/Setups (Feature Request)

### ISSUE THREAD

**Issue by manu-chroma** [bhrigu123/classifier#25]
Create another folder for saving all the program setup files like in case of windows ('.exe' , '.msi' , etc.)
or the setup files can be clubbed into archives itself.

**Comment by sudheer594** [comment]
Instead of adding the custom formats in source code . it will be better,if classifier uses a configuration file.This way , User can add or update the formats on need.

**Comment by psachin** [comment]
@sudheer594 

This is handled in Issue #17

**Comment by sudheer594** [comment]
@psachin thanks

**Comment by psachin** [comment]
Fixed #30
