### ISSUE TITLE
.tar.gz files not being moved

### ISSUE THREAD

**Issue by manu-chroma** [bhrigu123/classifier#26]
Files of type``` file.tar.gz ``` get split like``` filename = file.tar and file_ext = .gz ``` and thus don't get moved in specified folders.

**Comment by bhrigu123** [comment]
Hi, this issue was fixed in one of the recent commits, and the package was upgraded later.
Did you install classifier earlier?
If so, try upgrading it and try again if it works.
`sudo pip install classifier --upgrade`

**Comment by manu-chroma** [comment]
Yeah, it works now!
