### ISSUE TITLE
Lol had the same idea as you guys

### ISSUE THREAD

**Issue by Toltar** [bhrigu123/classifier#40]
I had the same idea here a little while back: [Mine but with something similar](https://github.com/Toltar/DownloadsOrganizer)

I did not know you this existed. But I was having trouble finding where I could make this run in the background of all OS's. But I'd thought I just say thanks for making this! You did more of a better job for what I have accomplished so far in my repository. If there is any issues you need fixing, I will fix it.

**Comment by bhrigu123** [comment]
Sure :+1: :)
