### ISSUE TITLE
How to Customize Settings Type by myself？

### ISSUE THREAD

**Issue by pcwuyu** [bhrigu123/classifier#47]
i want .torrent to 种子文件 and .wav to Audio and .exe to WinSoftware .etc

how to config it?

**Comment by bhrigu123** [comment]
Hi, for now this feature is not available. One will have to run the _ specific type_ command again and again( `classifier -st .wav -sf "Audio"` )
We could work on it in the future. The problem is that, since this is just a script that runs, we need to have another config file saved in the user's machine, and is easy for him to configure/change...or do it any other way.

**Comment by pcwuyu** [comment]
where can i config the classifier.py?

**Comment by pcwuyu** [comment]
sorry,my english is poor.

**Comment by pcwuyu** [comment]
![_929](https://cloud.githubusercontent.com/assets/6291329/12721682/eca6eb58-c93b-11e5-8032-c28fc51fa8e6.png)
can i config this and run setup.py again?

**Comment by bhrigu123** [comment]
Oh yes. You can also install by downloading this package, edit the code as per your requirements, and install as `python setup.py install`
(don't install using pip then)

**Comment by pcwuyu** [comment]
should i run ` pip uninstall ` first?

**Comment by bhrigu123** [comment]
Yes, first uninstall the previous version.
`pip uninstall classifier`

**Comment by pcwuyu** [comment]
the last questin,

- i run `pip install classifier`
- when i type `classifier` and run it in the terminal 
- will it run some .py file ?can i config it?

**Comment by bhrigu123** [comment]
Yes. Running `pip` installs our python package, and will put the `.py` file somewhere in our root directory, from where python packages could be run directly.
It would be different on different machines where that .py file is kept.
For example, in my Ubuntu machine, the file is in:
`/usr/local/lib/python2.7/dist-packages/classifier-1.6-py2.7.egg/classifier/classifier.py`

It generally installs in a location like this....search where python2.7 folder is in your computer...and the different installed packages are kept inside it somewhere.

You can edit the file (using root permissions), and next time you run `classifier`, it would run that file only (updated).

**Comment by pcwuyu** [comment]
Thank you very much for your explanation.I use Archlinux.

**Comment by bhrigu123** [comment]
No problem.
