### ISSUE TITLE
Classify installers (for downloads folder)

### ISSUE THREAD

**Issue by FreddieV4** [bhrigu123/classifier#54]
Hi. I ran `classifier` in my **Downloads** folder just now and was wondering if there'd be a way to classify installers (normally I'd just delete them but I figured this wouldn't be a bad idea, especially if you're using it on a **Downloads** folder)

**Comment by bhrigu123** [comment]
You're talking about `.exe` file types? or any other ?

**Comment by FreddieV4** [comment]
`.exe`, `.msi`, etc etc
