### ISSUE TITLE
[Feature] Specific file types only sorted

### ISSUE THREAD

**Issue by lepickle** [bhrigu123/classifier#6]
I think we should add an option for users to sort specific files/file types/categories into their own folders.

For example: classifier -S *.py *.pyc "Python Files"

This will sort all py and pyc files into a folder named "Python Files" without touching the rest of the files.

**Comment by bhrigu123** [comment]
Hi, (sorry for being late, I was caught up in something)
I have pushed the changes in the commit 37d32ec05469afaf9f60c3b6e3849d50bfb253bf
You can check it out.
If everything looks fine I would update the Python package on PyPi.

**Comment by bhrigu123** [comment]
Also I should mention that we cannot use asterisk (*) while sending the arguments (without escaping it), as it has meaning for the shell.
Instead, the command will be like;
`classifier -s .py .pyc "Python Files" `
Plus it looks cleaner.
