### ISSUE TITLE
add option which directory to classifier

### ISSUE THREAD

**Issue by maonx** [bhrigu123/classifier#66]
I use classifier in crontab tasks, I want PC to auto classifier, so maybe add a option to set which directory to classifier?

**Comment by bhrigu123** [comment]
Yeah. This could be useful. Will look into it.

**Comment by bhrigu123** [comment]
Hi, sorry for being late. This feature has been added in commit 9f14f78.
You can use this by upgrading your current classifier to the latest version.
Usage is explained in the README at https://github.com/bhrigu123/classifier#example-3
