### ISSUE TITLE
does not run

### ISSUE THREAD

**Issue by lack3r** [bhrigu123/classifier#67]
Program does not run on my pc, because of a typo. If you see the following line "'Videos': ['.flv', '.ogv', '.avi', '.mp4', '.mpg', '.mpeg', '.3gp', '.mkv', '.ts', , '.webm', '.vob', '.wmv'],"

you will see that there are two commas before webm.

Excellent project!:)

**Comment by bhrigu123** [comment]
Oh. Must've got there when I was just adding some new formats.
Fixed it and upgraded on PyPi.
